spring.application.name=invoice-consumer
spring.main.web-application-type=none

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=faturamento-group
spring.kafka.consumer.auto-offset-reset=earliest

#spring.datasource.url=${DB_ORACLE_URL:jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-saopaulo-1.oraclecloud.com))(connect_data=(service_name=g3f22f117d807df_wclp_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))?TNS_ADMIN=/home/wcl/oracle_wallet}
spring.datasource.url=${DB_ORACLE_URL:jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-saopaulo-1.oraclecloud.com))(connect_data=(service_name=g3f22f117d807df_wclp_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(javax.net.ssl.keyStorePassword=${WALLET_PASS})(javax.net.ssl.trustStorePassword=${WALLET_PASS})))?TNS_ADMIN=/home/wcl/oracle_wallet}
#spring.datasource.url=${DB_ORACLE_URL:jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-saopaulo-1.oraclecloud.com))(connect_data=(service_name=g3f22f117d807df_wclp_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(javax.net.ssl.keyStorePassword=${WALLET_PASS})(javax.net.ssl.trustStorePassword=${"Estudos#OCI#2026"})))?TNS_ADMIN=/home/wcl/oracle_wallet}
spring.datasource.username=${DB_ORACLE_USER:ADMIN}
spring.datasource.password=${DB_ORACLE_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# como implantei a funcionalidade  download, precisei transformar esse servico em web
spring.main.web-application-type=servlet

# CONFIGURACOES DO ORACLE OBJECT STORAGE
oci.tenant.namespace=${OCI_NAMESPACE:grzkmpyddqgg}
oci.bucket.name=${OCI_BUCKET_NAME:billing-queue-bucket}

# CONFIGURACAO DE SEGURANCA DA WALLET ORACLE (mTLS)
#spring.datasource.oracle.net.wallet_password=${WALLET_PASS}

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update


# Configuracao do Deserializador (Transforma o JSON do Kafka de volta em objeto Java)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Pacotes permitidos para conversao de JSON (Tratamento de seguranca do Spring)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Logs de SQL ativos para desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082
